# Openduckbill configuration file. 
# This is an YAML file and has four different sections
#
# ----- Global variable declaration section ----
global :
# Backup method
# How we will access the backup server. This can be LOCAL|NFS|RSYNC
# Also define a section below with server, remote and local mount paths
 backupmethod : LOCAL
# Time in seconds
 syncinterval : 300
# Wait for these many filesystem changes to occur. Integer
 commitchanges : 64
# Keep a backup of files which were synced to backup destination. The backup
# files will have a file extention ".odb~". Openduckbill maintains an exact copy
# of the entries in the backup directory. If "maintainprevious" is specified as "yes"
# openduckbill will keep another copy of the modified file. In effect, openduckbill
# will maintain the current and previous version of the modified file at the backup 
# destination. This will increase the # disk usage at the destination. [Boolean] [yes|no]
 maintainprevious : no
# Retain files/directories which are not in the scheduled list? [Boolean] [yes|no]
# Default is yes
 retainbackup : yes
# When entries are removed from backup schedule, these remain
# in the backup drive and are no longer backed up. If there are
# files/directories which are older than "retentiontime" and,
# not in the schedule (entry list) to be backed up, then these
# are removed. (seconds) [Default = 7 Days = 604800 Seconds]
# Valid if "retainbackup" is yes
 retentiontime : 604800 

# ----- Backup method declaration section ----
LOCAL :
# Some directory on localmachine. This could be an NFS hard mount.
 localmount : "/backup/odb_backup"

NFS :
# Make sure you have the following line in your /etc/fstab
#
# $server:$remotemount $localmount  nfs  $nfsmountoptions,user,auto  0 0
#
# The reason being, openduckbill tries to run the command `mount $localmount`,
# which doesn't require password if the line is already mentioned in /etc/fstab
# Replace $server, $remotemount, $localmount with values mentioned below.
#
# While modifying the server address, make sure to update entry in /etc/fstab
# NFS server (FQDN)
 server : "server1.mydomain.com"
# Remote NFS exported partition
 remotemount : "/backup/odb_server1"
# Local mount point for the NFS partition
 localmount : "/mnt/odb_mount"
# Other NFS mount options (comma separated, within quotes. eg. "rw,nosuid")
 nfsmountoptions : "rw,nosuid,soft"

# RSYNC over SSH
RSYNC :
# SSH server (FQDN)
 server : "server2.mydomain.com"
# ssh server port (mention port number if your server is running on a 
# non-standard port. Default is 22)
 sshport : 22
# Remote directory path on server
 remotemount : "/backup/odb_server2"

# ----- Exclude declaration section ----
# Files/directories to be excluded from backup paths defined in "entry" section.
exclude :
 - "*.mp3"
 - "*.mp4"
 - "*.jpg"
 - "*.jpeg"
 - "*.png"
 - "*.gif"
 - "*.log*"

# ----- Backup entry declaration section ----
# Backup entries
# recursive : yes | no
# Per entry include, exlcude : same format as toplevel exclude declaration
#   Use absolute paths for better pattern matching. :-)
entry :
 - name : home_backup
   path : "~/"
   recursive : no
   include :
    - "*.log*"
 - name : docs_backup
   path : "~/Documents"
   recursive : yes
   exclude :
    - "*~"
    - "~/Documents/Personal/*"
 - name : projects_backup
   path : "~/Projects/"
   recursive : yes
   include :
    - "*.gif"
